export const siteConfig = {
  name: "Ekam Singh Bhatia",
  title: "Full Stack Developer",
  description: "Portfolio website of Ekam",
  accentColor: "#1d4ed8",
  social: {
    email: "ekamsingh643@gmail.com",
    linkedin: "https://www.linkedin.com/in/ekam-singh-335840168/",
    github: "https://github.com/bhat0155",
  },
  aboutMe:
    "I’m a recent Mobile Application Design & Development graduate from Algonquin College and a full-stack developer who loves building everything I can think of—from web apps to mobile experiences. Skilled in React, Next.js, Node.js, Prisma, and PostgreSQL, I focus on creating scalable, user-centered products with clean architecture and thoughtful design. I’m driven by curiosity, creativity, and the excitement of turning ideas into real, impactful solutions.",
  skills: [
    "JavaScript",
    "TypeScript",
    "React",
    "Next.js",
    "Node.js",
    "Express",
    "Prisma",
    "PostgreSQL",
    "AWS (EC2, S3, CloudFront)",
    "Tailwind CSS",
    "Firebase",
    "SwiftUI",
    "Flutter",
    "Git & GitHub",
    "Figma",
  ],
  projects: [
    {
      name: "Bhangrascape.ca",
      description:
        "BhangraEscape.ca — a full-stack event and community platform built with Next.js, Prisma, and AWS, connecting dancers and organizers through interactive polls, media sharing, and event management.",
      link: "https://bhangrascape.ca/",
      skills: [
        "Next.js",
        "TypeScript",
        "Prisma",
        "PostgreSQL",
        "Node.js",
        "Express",
        "AWS (S3, EC2, CloudFront)",
        "Tailwind CSS",
        "DaisyUI",
        "NextAuth.js",
      ],
    },
    {
      name: "AI Model Playground",
      description:
        "A real-time AI comparison platform built with Next.js and NestJS, streaming responses from multiple models side-by-side with live metrics, performance insights, and cost tracking.",
      link: "https://a-idifferentiator.vercel.app/",
      skills: [
        "Next.js",
        "NestJS",
        "TypeScript",
        "Prisma",
        "PostgreSQL",
        "Server-Sent Events (SSE)",
        "React",
        "Tailwind CSS",
        "Zustand",
        "RxJS",
        "Markdown Rendering",
        "Vercel",
        "Render",
      ],
    },
    {
      name: "Movie-Recomender",
      description:
        "An AI-powered Netflix clone built with React, Tailwind, Firebase, Redux, and the TMDB + OpenAI APIs, enabling users to browse, search, and get GPT-driven movie recommendations with full authentication and responsive design.",
      link: "https://aimovierecommendation.netlify.app/",
      skills: [
        "React",
        "Redux Toolkit",
        "Tailwind CSS",
        "Firebase Authentication",
        "TMDB API",
        "OpenAI API",
        "JavaScript (ES6+)",
        "Vite",
        "Responsive Design",
      ],
    },
  ],
  experience: [
    {
      company: "The Beer Store",
      title: "Warehouse Clerk (Co-op)",
      dateRange: "Aug 2023 - Dec 2023",
      bullets: [
        "Maintained 98% accuracy in inventory audits, developing strong attention to detail — a skill I now apply when debugging complex code and verifying data integrity in backend systems.",
        "Collaborated with cross-functional teams to reduce product handling time by 15%, mirroring agile teamwork and iteration cycles used in software development.",
        "Operated digital inventory systems efficiently, reinforcing my understanding of structured data handling and process optimization.",
      ],
    },
    {
      company: "Amazon",
      title: "Seller Support Associate",
      dateRange: "Oct 2020 - Nov 2022",
      bullets: [
        "Handled over 1,000 tax-related support cases for EU sellers with a 95% resolution rate, enhancing my analytical thinking and ability to troubleshoot complex problems under pressure.",
        "Adapted quickly to advanced internal tools and workflows, strengthening my capacity to learn new technologies and development frameworks efficiently.",
        "Authored SOP documentation that reduced new hire ramp-up time by 20%, demonstrating my commitment to clarity and maintainability — principles I apply when writing clean, well-documented code.",
      ],
    },
  ],
  education: [
    {
      school: "Algonquin College",
      degree: "Mobile Application Design and Development",
      dateRange: "2024–2025",
      achievements: [
        "Graduated Magna Cum Laude with a 3.7 GPA",
        "Dean's List in all semesters",
      ],
    },
    {
      school: "Algonquin College",
      degree: "Post-Graduate Certificate in Supply Chain Management",
      dateRange: "2023",
      achievements: [
        "Graduated Magna Cum Laude with a 3.65 GPA",
        "Dean's List in all semesters",
      ],
    },
  ],
};