export const siteConfig = {
  name: "Ekam Bhatia",
  title: "Cloud & DevOps Engineer | Full-Stack Developer",
  description: "Portfolio of Ekam Bhatia — Full-Stack Developer with cloud & DevOps depth",
  accentColor: "#1d4ed8",
  social: {
    email: "ekamsingh643@gmail.com",
    linkedin: "https://www.linkedin.com/in/ekam-bhatia-335840168/",
    github: "https://github.com/bhat0155",
    blog: "https://www.ekamblogs.ca/",
  },
  aboutMe:
    "I'm a full-stack developer who builds end-to-end web applications and owns them all the way through to production. My core stack is React, Next.js, Node.js, and PostgreSQL, and I care about clean, maintainable code and user-centered design. What sets me apart from a typical full-stack developer is the DevOps side: I'm Microsoft Azure (AZ-900) certified and comfortable across the whole delivery lifecycle — provisioning infrastructure with Terraform, containerizing with Docker and Kubernetes, building CI/CD pipelines with Jenkins, GitHub Actions, and Azure Pipelines, and adding observability with Prometheus and Grafana. I also work with AWS (EC2, S3) and bring a mobile-development foundation from my diploma. I write about my cloud and DevOps work in depth on my blog, and I'm focused on turning complex requirements into streamlined, production-ready systems.",
  skills: [
    "JavaScript",
    "TypeScript",
    "React",
    "Next.js",
    "Node.js",
    "Express",
    "Prisma",
    "PostgreSQL",
    "Microsoft Azure (AZ-900)",
    "AWS (EC2, S3)",
    "Terraform",
    "Docker",
    "Kubernetes (AKS)",
    "Jenkins",
    "GitHub Actions",
    "Argo CD (GitOps)",
    "Prometheus & Grafana",
    "CI/CD",
    "Tailwind CSS",
    "Firebase",
    "Git & GitHub",
    "Figma",
  ],
  projects: [
    {
      name: "Bhangrascape.ca",
      description:
        "A full-stack event and community platform I designed, built, and deployed solo for a performing-arts team. Built with Next.js, Node.js, PostgreSQL, and Prisma, it centralizes event scheduling, member coordination, interactive polls, and media sharing — with secure uploads via AWS S3 presigned URLs and authentication through JWT, Google OAuth, and role-based access control. I own the full delivery pipeline: environment configuration, CI/CD, and continuous production releases across Vercel and Render.",
      link: "https://bhangrascape.ca/",
      skills: [
        "Next.js",
        "TypeScript",
        "Prisma",
        "PostgreSQL",
        "Node.js",
        "Express",
        "AWS S3 (presigned URLs)",
        "JWT / Google OAuth / RBAC",
        "Tailwind CSS",
        "CI/CD",
        "Vercel",
        "Render",
      ],
    },
    {
      name: "Receipt-Checker",
      description:
        "A full-stack receipt-intelligence tool: users upload a grocery receipt, the backend extracts items using Google Vision OCR and an LLM, then checks them against recent Canadian recall data. Built with React + Vite on the frontend and Node.js/Express, Prisma, and PostgreSQL on the backend. The live app runs on AWS EC2 with Nginx, HTTPS, PM2, response caching, automated cleanup jobs, and a GitHub Actions CI/CD pipeline. As a separate infrastructure exercise, I also provisioned the full stack on Azure using reusable Terraform modules (App Service, PostgreSQL Flexible Server, storage, firewall rules) and built a two-stage Jenkins CI/CD pipeline handling cross-platform builds, tests, prisma migrate deploy, secrets injection, and post-deploy liveness-probe validation.",
      link: "https://receiptchecker.ca/",
      skills: [
        "React",
        "TypeScript",
        "Tailwind CSS",
        "Express",
        "Prisma ORM",
        "PostgreSQL",
        "Google Cloud Vision API",
        "OpenAI / LLM Integration",
        "AWS (EC2, Nginx, HTTPS, PM2)",
        "Azure App Service",
        "Terraform",
        "Jenkins CI/CD",
        "GitHub Actions",
      ],
    },
    {
      name: "XEffect",
      description:
        "A full-stack 21-day habit tracker with a public progress page and a private authenticated dashboard — powered by Google OAuth, JWT cookie sessions, a streak engine, and AI-generated milestone messages for motivation. Built with React, Node.js/Express, Prisma, and PostgreSQL, documented with Swagger/OpenAPI. The live app is deployed across Vercel (frontend) and Render (backend). As a separate infrastructure exercise, I also containerized every tier with multi-stage Docker builds and authored custom Kubernetes manifests (Deployments, Services, ConfigMaps, Ingress, PVCs), then automated delivery through a GitOps pipeline — Azure Pipelines building and pushing images to Azure Container Registry, with Argo CD syncing them onto an AKS cluster on every commit.",
      link: "https://xeffect.ca/",
      skills: [
        "React",
        "TypeScript",
        "Tailwind CSS",
        "Express",
        "Node.js",
        "Prisma",
        "PostgreSQL",
        "Google OAuth",
        "JWT",
        "Swagger/OpenAPI",
        "Vercel",
        "Render",
        "Docker",
        "Kubernetes (AKS)",
        "Argo CD (GitOps)",
        "Azure Pipelines",
      ],
    },
  ],
  experience: [
    {
      company: "The Beer Store",
      title: "Warehouse Clerk (Co-op)",
      dateRange: "Aug 2023 - Dec 2023",
      bullets: [
        "Maintained 98% accuracy in inventory audits, developing strong attention to detail — a skill I now apply when debugging complex code and verifying data integrity in backend systems.",
        "Collaborated with cross-functional teams to reduce product handling time by 15%, mirroring agile teamwork and iteration cycles used in software development.",
        "Operated digital inventory systems efficiently, reinforcing my understanding of structured data handling and process optimization.",
      ],
    },
    {
      company: "Amazon",
      title: "Technical Support Associate",
      dateRange: "Oct 2020 - Nov 2022",
      bullets: [
        "Resolved 1,000+ technical support cases with a 95% resolution rate, applying structured troubleshooting and root-cause analysis under strict SLAs — habits that carry directly into debugging and incident response.",
        "Adapted quickly to complex internal tools and workflows, strengthening my ability to ramp on new technologies and frameworks efficiently.",
        "Authored SOP documentation that cut new-hire ramp-up time by 20%, reflecting a focus on clarity and maintainability that I bring to writing clean, well-documented code.",
      ],
    },
  ],
  education: [
    {
      school: "Algonquin College",
      degree: "Advanced Diploma, Mobile Application Design and Development",
      dateRange: "2024–2025",
      achievements: [
        "Graduated Magna Cum Laude with a 3.7 GPA",
        "Dean's List in all semesters",
      ],
    },
    {
      school: "Algonquin College",
      degree: "Post-Graduate Certificate in Supply Chain Management",
      dateRange: "2023",
      achievements: [
        "Graduated Magna Cum Laude with a 3.65 GPA",
        "Dean's List in all semesters",
      ],
    },
  ],
};